name: workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend tests and coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run tests with coverage
        run: mvn clean test jacoco:report

  frontend-tests:
    name: Frontend tests and coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test -- --code-coverage

