name: workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  # =====================
  # TESTS AND COVERAGE
  # =====================

  backend-tests:
    name: Backend tests and coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run tests with coverage
        run: mvn clean test jacoco:report


  frontend-tests:
    name: Frontend tests and coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

  # =====================
  # DEPLOY IMAGES
  # =====================

  deploy-backend:
    name: Build and push backend docker image
    runs-on: ubuntu-latest
    needs: backend-tests
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest


  deploy-frontend:
    name: Build and push frontend Docker Image
    runs-on: ubuntu-latest
    needs: frontend-tests
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: front
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest